version: "3"

services:
  jupyter:
    build: .
    environment:
      - PYTHONPATH=/project
    ports:
      - "8888:8888"
    volumes:
      - ./:/project
    command: /opt/conda/bin/jupyter notebook --notebook-dir=/project --ip='0.0.0.0' --port=8888 --no-browser --allow-root
